
arq = open('pokemon.arff', 'r')
salva = open('pokemonNew.arff', 'w')
texto = arq.read()
database = texto.split('\n')

print(texto)

texto = texto.replace(',Grass,', ',1,')
texto = texto.replace(',Fire,', ',2,')
texto = texto.replace(',Water,', ',3,')
texto = texto.replace(',Bug,', ',4,')
texto = texto.replace(',Normal,', ',5,')
texto = texto.replace(',Poison,', ',6,')
texto = texto.replace(',Electric,', ',7,')
texto = texto.replace(',Ground,', ',8,')
texto = texto.replace(',Fighting,', ',9,')
texto = texto.replace(',Psychic,', ',10,')
texto = texto.replace(',Rock,', ',11,')
texto = texto.replace(',Flying,', ',12,')
texto = texto.replace(',Ghost,', ',13,')
texto = texto.replace(',Ice,', ',14,')
texto = texto.replace(',Dragon,', ',15,')
texto = texto.replace(',Steel,', ',16,')
texto = texto.replace(',Dark,', ',17,')
texto = texto.replace(',Fairy,', ',18,')

texto = texto.replace(',Grass,', ',1,')
texto = texto.replace(',Fire,', ',2,')
texto = texto.replace(',Water,', ',3,')
texto = texto.replace(',Bug,', ',4,')
texto = texto.replace(',Normal,', ',5,')
texto = texto.replace(',Poison,', ',6,')
texto = texto.replace(',Electric,', ',7,')
texto = texto.replace(',Ground,', ',8,')
texto = texto.replace(',Fighting,', ',9,')
texto = texto.replace(',Psychic,', ',10,')
texto = texto.replace(',Rock,', ',11,')
texto = texto.replace(',Flying,', ',12,')
texto = texto.replace(',Ghost,', ',13,')
texto = texto.replace(',Ice,', ',14,')
texto = texto.replace(',Dragon,', ',15,')
texto = texto.replace(',Steel,', ',16,')
texto = texto.replace(',Dark,', ',17,')
texto = texto.replace(',Fairy,', ',18,')

texto = texto.replace(',AG,', ',1,')
texto = texto.replace(',BL,', ',2,')
texto = texto.replace(',BL2,', ',3,')
texto = texto.replace(',LC,', ',4,')
texto = texto.replace(',Limbo,', ',5,')
texto = texto.replace(',NU,', ',6,')
texto = texto.replace(',OU,', ',7,')
texto = texto.replace(',PU,', ',8,')
texto = texto.replace(',RU,', ',9,')
texto = texto.replace(',Uber,', ',10,')
texto = texto.replace(',UU,', ',11,')
texto = texto.replace(',-,', ',12,')

print(texto)

salva.write(texto)
arq.close()
salva.close()
